name: Run Tidy

on:
  push:
    paths-ignore:
      - '.github/workflows/clean_bmg.yml'
      - '.github/workflows/build_sp.yml'
  pull_request:
    paths-ignore:
      - '.github/workflows/clean_bmg.yml'
      - '.github/workflows/build_sp.yml'

jobs:
  tidy:
    name: Run Tidy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Tidy
        run: python3 tools/tidy/main.py
